import type { Tables, Product } from "@/types/database";

const cat = (id: string, name: string, description: string, image_url: string): Tables<"categories"> => ({
  id, name, description, image_url, created_at: new Date().toISOString(),
});

const ing = (id: string, name: string, is_allergen: boolean): Tables<"ingredients"> => ({
  id, name, is_allergen, created_at: new Date().toISOString(),
});

function makeProduct(
  id: string,
  categoryId: string,
  name: string,
  description: string,
  calories: number,
  variants: { label: string; weight: number; price: number }[],
  ingredientIds: string[],
  imgSeed: string,
): { product: Tables<"products">; variants: Tables<"product_variants">[]; ingredientIds: string[] } {
  return {
    product: {
      id,
      category_id: categoryId,
      name,
      description,
      image_url: `https://placehold.co/400x400/FEF3C7/78350F?text=${encodeURIComponent(imgSeed)}`,
      calories,
      is_available: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    variants: variants.map((v, i) => ({
      id: `${id}-v${i + 1}`,
      product_id: id,
      label: v.label,
      weight_grams: v.weight,
      price: v.price,
      stock: 50,
      created_at: new Date().toISOString(),
    })),
    ingredientIds,
  };
}

export const MOCK_CATEGORIES: Tables<"categories">[] = [
  cat("cat-1", "Barfi", "Traditional milk-based Indian sweets with rich, creamy textures", "https://placehold.co/400x300/FEF3C7/78350F?text=Barfi"),
  cat("cat-2", "Ladoo", "Round ball-shaped sweets made from flour, sugar, and ghee", "https://placehold.co/400x300/FDE68A/78350F?text=Ladoo"),
  cat("cat-3", "Halwa", "Dense, sweet confections made with flour, ghee, and sugar", "https://placehold.co/400x300/FCD34D/78350F?text=Halwa"),
  cat("cat-4", "Dry Fruit Sweets", "Premium sweets made with dry fruits and nuts", "https://placehold.co/400x300/FBBF24/78350F?text=Dry+Fruits"),
  cat("cat-5", "Mithai Box", "Curated assorted sweet boxes for gifting", "https://placehold.co/400x300/F59E0B/78350F?text=Mithai+Box"),
  cat("cat-6", "Bengali Sweets", "Famous sweets from the Bengali tradition", "https://placehold.co/400x300/D97706/FEF3C7?text=Bengali"),
  cat("cat-7", "Milk Cakes", "Rich milk-based cakes and peda varieties", "https://placehold.co/400x300/B45309/FEF3C7?text=Milk+Cakes"),
  cat("cat-8", "Chocolate Fusion", "Traditional sweets with a modern chocolate twist", "https://placehold.co/400x300/92400E/FEF3C7?text=Choco+Fusion"),
];

export const MOCK_INGREDIENTS: Tables<"ingredients">[] = [
  ing("ing-1", "Milk", true),
  ing("ing-2", "Sugar", false),
  ing("ing-3", "Ghee", true),
  ing("ing-4", "Almonds", true),
  ing("ing-5", "Cashews", true),
  ing("ing-6", "Pistachios", true),
  ing("ing-7", "Cardamom", false),
  ing("ing-8", "Saffron", false),
  ing("ing-9", "Besan (Gram Flour)", false),
  ing("ing-10", "Wheat Flour", true),
  ing("ing-11", "Coconut", true),
  ing("ing-12", "Rose Water", false),
  ing("ing-13", "Silver Leaf (Vark)", false),
  ing("ing-14", "Khoya (Mawa)", true),
  ing("ing-15", "Dates", false),
  ing("ing-16", "Semolina", true),
  ing("ing-17", "Jaggery", false),
  ing("ing-18", "Paneer (Cottage Cheese)", true),
  ing("ing-19", "Cocoa Powder", false),
  ing("ing-20", "Dark Chocolate", true),
  ing("ing-21", "Walnuts", true),
  ing("ing-22", "Raisins", false),
  ing("ing-23", "Condensed Milk", true),
];

const RAW_PRODUCTS = [
  makeProduct("p-1", "cat-1", "Kaju Barfi", "Premium cashew fudge garnished with silver leaf. Melt-in-mouth texture with the rich flavor of roasted cashews.", 320,
    [{ label: "250g Box", weight: 250, price: 350 }, { label: "500g Box", weight: 500, price: 650 }, { label: "1kg Box", weight: 1000, price: 1200 }],
    ["ing-5", "ing-2", "ing-3", "ing-7", "ing-13"], "Kaju+Barfi"),
  makeProduct("p-2", "cat-1", "Pista Barfi", "Delicate pistachio barfi with a beautiful green hue. Made with hand-picked pistachios and pure ghee.", 290,
    [{ label: "250g Box", weight: 250, price: 400 }, { label: "500g Box", weight: 500, price: 750 }, { label: "1kg Box", weight: 1000, price: 1400 }],
    ["ing-6", "ing-2", "ing-3", "ing-7", "ing-1"], "Pista+Barfi"),
  makeProduct("p-3", "cat-1", "Badam Barfi", "Almond barfi made with blanched almonds, milk, and aromatic cardamom. A classic celebration sweet.", 310,
    [{ label: "250g Box", weight: 250, price: 380 }, { label: "500g Box", weight: 500, price: 700 }, { label: "1kg Box", weight: 1000, price: 1300 }],
    ["ing-4", "ing-2", "ing-3", "ing-7", "ing-1", "ing-8"], "Badam+Barfi"),
  makeProduct("p-4", "cat-1", "Coconut Barfi", "Soft coconut barfi with condensed milk and a hint of cardamom. Topped with sliced almonds.", 275,
    [{ label: "250g Box", weight: 250, price: 220 }, { label: "500g Box", weight: 500, price: 400 }],
    ["ing-11", "ing-23", "ing-7", "ing-4"], "Coconut+Barfi"),
  makeProduct("p-5", "cat-1", "Chocolate Barfi", "Classic barfi infused with Belgian cocoa. A fusion of Indian tradition and chocolate indulgence.", 340,
    [{ label: "250g Box", weight: 250, price: 300 }, { label: "500g Box", weight: 500, price: 550 }],
    ["ing-14", "ing-19", "ing-2", "ing-3"], "Choco+Barfi"),
  makeProduct("p-6", "cat-2", "Motichoor Ladoo", "Iconic golden ladoos made from tiny boondi pearls soaked in saffron-infused sugar syrup.", 350,
    [{ label: "250g (6 pcs)", weight: 250, price: 200 }, { label: "500g (12 pcs)", weight: 500, price: 380 }, { label: "1kg (24 pcs)", weight: 1000, price: 720 }],
    ["ing-9", "ing-2", "ing-3", "ing-8", "ing-7", "ing-12"], "Motichoor"),
  makeProduct("p-7", "cat-2", "Besan Ladoo", "Traditional gram flour ladoos roasted in pure ghee with cardamom and topped with almonds.", 380,
    [{ label: "250g (6 pcs)", weight: 250, price: 180 }, { label: "500g (12 pcs)", weight: 500, price: 340 }, { label: "1kg (24 pcs)", weight: 1000, price: 650 }],
    ["ing-9", "ing-2", "ing-3", "ing-7", "ing-4"], "Besan+Ladoo"),
  makeProduct("p-8", "cat-2", "Coconut Ladoo", "Soft and chewy ladoos made with fresh grated coconut, condensed milk, and cardamom.", 260,
    [{ label: "250g (8 pcs)", weight: 250, price: 160 }, { label: "500g (16 pcs)", weight: 500, price: 300 }],
    ["ing-11", "ing-2", "ing-1", "ing-7"], "Coconut+Ladoo"),
  makeProduct("p-9", "cat-2", "Dry Fruit Ladoo", "Nutrient-rich ladoos packed with almonds, cashews, walnuts, dates, and honey. No refined sugar.", 295,
    [{ label: "250g (6 pcs)", weight: 250, price: 350 }, { label: "500g (12 pcs)", weight: 500, price: 650 }],
    ["ing-4", "ing-5", "ing-21", "ing-15", "ing-17"], "DryFruit+Ladoo"),
  makeProduct("p-10", "cat-2", "Rava Ladoo", "Semolina ladoos with ghee, sugar, and raisins. Crunchy on the outside, soft inside.", 330,
    [{ label: "250g (6 pcs)", weight: 250, price: 170 }, { label: "500g (12 pcs)", weight: 500, price: 320 }],
    ["ing-16", "ing-2", "ing-3", "ing-22", "ing-5"], "Rava+Ladoo"),
  makeProduct("p-11", "cat-3", "Gajar Ka Halwa", "Rich carrot halwa slow-cooked with milk, ghee, and dry fruits. A winter delicacy.", 340,
    [{ label: "250g", weight: 250, price: 220 }, { label: "500g", weight: 500, price: 420 }, { label: "1kg", weight: 1000, price: 800 }],
    ["ing-1", "ing-2", "ing-3", "ing-7", "ing-4", "ing-5"], "Gajar+Halwa"),
  makeProduct("p-12", "cat-3", "Moong Dal Halwa", "Luxurious moong dal halwa made with split green gram, ghee, and garnished with almonds.", 400,
    [{ label: "250g", weight: 250, price: 280 }, { label: "500g", weight: 500, price: 520 }],
    ["ing-3", "ing-2", "ing-1", "ing-4", "ing-7"], "Moong+Halwa"),
  makeProduct("p-13", "cat-3", "Sooji Halwa", "Semolina halwa prepared with ghee, sugar, and saffron. Simple yet divine.", 300,
    [{ label: "250g", weight: 250, price: 150 }, { label: "500g", weight: 500, price: 280 }],
    ["ing-16", "ing-2", "ing-3", "ing-8", "ing-7"], "Sooji+Halwa"),
  makeProduct("p-14", "cat-3", "Badam Halwa", "Pure almond halwa cooked for hours until perfectly rich and dense. A royal treat.", 360,
    [{ label: "250g", weight: 250, price: 450 }, { label: "500g", weight: 500, price: 850 }],
    ["ing-4", "ing-2", "ing-3", "ing-8", "ing-7"], "Badam+Halwa"),
  makeProduct("p-15", "cat-4", "Anjeer Roll", "Premium fig rolls stuffed with dry fruits and coated with desiccated coconut.", 280,
    [{ label: "250g", weight: 250, price: 320 }, { label: "500g", weight: 500, price: 600 }],
    ["ing-15", "ing-5", "ing-4", "ing-11", "ing-7"], "Anjeer+Roll"),
  makeProduct("p-16", "cat-4", "Kaju Pista Roll", "Cashew and pistachio rolls with a beautiful layered look. Perfect for gifting.", 330,
    [{ label: "250g", weight: 250, price: 380 }, { label: "500g", weight: 500, price: 720 }],
    ["ing-5", "ing-6", "ing-2", "ing-3", "ing-7"], "Kaju+Pista+Roll"),
  makeProduct("p-17", "cat-4", "Date & Nut Bites", "Energy-packed bites made with Medjool dates, almonds, walnuts, and a touch of cocoa.", 240,
    [{ label: "200g (10 pcs)", weight: 200, price: 280 }, { label: "400g (20 pcs)", weight: 400, price: 520 }],
    ["ing-15", "ing-4", "ing-21", "ing-19"], "Date+Nut+Bites"),
  makeProduct("p-18", "cat-4", "Kaju Katli", "Thin diamond-shaped cashew slices with silver vark. The king of Indian sweets.", 310,
    [{ label: "250g Box", weight: 250, price: 380 }, { label: "500g Box", weight: 500, price: 720 }, { label: "1kg Box", weight: 1000, price: 1350 }],
    ["ing-5", "ing-2", "ing-13", "ing-7"], "Kaju+Katli"),
  makeProduct("p-19", "cat-6", "Rasgulla", "Soft, spongy cottage cheese balls soaked in light sugar syrup. Bengal's pride.", 186,
    [{ label: "500g (10 pcs)", weight: 500, price: 250 }, { label: "1kg (20 pcs)", weight: 1000, price: 450 }],
    ["ing-18", "ing-2", "ing-12", "ing-7"], "Rasgulla"),
  makeProduct("p-20", "cat-6", "Sandesh", "Delicate Bengali sweet made from fresh paneer, sugar, and saffron. Melt-in-mouth.", 210,
    [{ label: "250g (8 pcs)", weight: 250, price: 280 }, { label: "500g (16 pcs)", weight: 500, price: 520 }],
    ["ing-18", "ing-2", "ing-8", "ing-6"], "Sandesh"),
  makeProduct("p-21", "cat-6", "Chamcham", "Oval-shaped Bengali sweet soaked in flavored syrup and coated with coconut.", 230,
    [{ label: "500g (8 pcs)", weight: 500, price: 300 }, { label: "1kg (16 pcs)", weight: 1000, price: 560 }],
    ["ing-18", "ing-2", "ing-11", "ing-12"], "Chamcham"),
  makeProduct("p-22", "cat-6", "Rosogolla (Saffron)", "Premium saffron-infused rosogolla with a golden hue and delicate flavor.", 195,
    [{ label: "500g (10 pcs)", weight: 500, price: 320 }, { label: "1kg (20 pcs)", weight: 1000, price: 600 }],
    ["ing-18", "ing-2", "ing-8", "ing-7"], "Saffron+Rosogolla"),
  makeProduct("p-23", "cat-7", "Milk Cake", "Dense, caramelized milk cake made by slow-cooking milk for hours. Rich butterscotch flavor.", 350,
    [{ label: "250g", weight: 250, price: 200 }, { label: "500g", weight: 500, price: 380 }, { label: "1kg", weight: 1000, price: 720 }],
    ["ing-1", "ing-2", "ing-3", "ing-7"], "Milk+Cake"),
  makeProduct("p-24", "cat-7", "Kesar Peda", "Saffron-flavored peda made from condensed milk and ghee. A timeless classic.", 290,
    [{ label: "250g (8 pcs)", weight: 250, price: 240 }, { label: "500g (16 pcs)", weight: 500, price: 450 }],
    ["ing-14", "ing-2", "ing-3", "ing-8", "ing-7"], "Kesar+Peda"),
  makeProduct("p-25", "cat-7", "Mathura Peda", "Traditional peda from Mathura with a grainy texture and deep caramel notes.", 305,
    [{ label: "250g (8 pcs)", weight: 250, price: 220 }, { label: "500g (16 pcs)", weight: 500, price: 400 }],
    ["ing-14", "ing-2", "ing-3", "ing-7"], "Mathura+Peda"),
  makeProduct("p-26", "cat-8", "Chocolate Modak", "Ganpati's favorite sweet reimagined with dark chocolate and roasted coconut filling.", 290,
    [{ label: "250g (6 pcs)", weight: 250, price: 320 }, { label: "500g (12 pcs)", weight: 500, price: 600 }],
    ["ing-20", "ing-11", "ing-17", "ing-5"], "Choco+Modak"),
  makeProduct("p-27", "cat-8", "Chocolate Peda", "Khoya peda with a swirl of Belgian dark chocolate. Best of both worlds.", 315,
    [{ label: "250g (8 pcs)", weight: 250, price: 280 }, { label: "500g (16 pcs)", weight: 500, price: 520 }],
    ["ing-14", "ing-20", "ing-2", "ing-7"], "Choco+Peda"),
  makeProduct("p-28", "cat-8", "Chocolate Kaju Roll", "Cashew rolls coated in rich dark chocolate ganache. A bestselling fusion sweet.", 345,
    [{ label: "250g", weight: 250, price: 400 }, { label: "500g", weight: 500, price: 750 }],
    ["ing-5", "ing-20", "ing-2", "ing-3"], "Choco+Kaju+Roll"),
  makeProduct("p-29", "cat-5", "Royal Assorted Box", "Curated box with our finest sweets - Kaju Barfi, Motichoor Ladoo, Pista Barfi, and more.", 300,
    [{ label: "500g Box", weight: 500, price: 550 }, { label: "1kg Box", weight: 1000, price: 1000 }, { label: "2kg Premium Box", weight: 2000, price: 1900 }],
    ["ing-5", "ing-6", "ing-4", "ing-1", "ing-3", "ing-2"], "Royal+Assorted"),
  makeProduct("p-30", "cat-5", "Festive Gift Hamper", "Premium hamper with 6 varieties of sweets in a designer box. Perfect for Diwali and weddings.", 310,
    [{ label: "1kg Box", weight: 1000, price: 1200 }, { label: "2kg Box", weight: 2000, price: 2200 }, { label: "3kg Grand Box", weight: 3000, price: 3200 }],
    ["ing-5", "ing-6", "ing-4", "ing-14", "ing-8", "ing-3"], "Festive+Hamper"),
  makeProduct("p-31", "cat-5", "Wedding Special Box", "Elegant wedding sweet box with Kaju Katli, Motichoor, Barfi, and Dry Fruit Roll.", 320,
    [{ label: "1kg Box", weight: 1000, price: 1100 }, { label: "2kg Box", weight: 2000, price: 2000 }],
    ["ing-5", "ing-9", "ing-14", "ing-15", "ing-3", "ing-13"], "Wedding+Box"),
  makeProduct("p-32", "cat-2", "Pinni", "Wholesome Punjabi sweet made with wheat flour, desi ghee, and dry fruits. Winter special.", 410,
    [{ label: "250g (4 pcs)", weight: 250, price: 200 }, { label: "500g (8 pcs)", weight: 500, price: 380 }],
    ["ing-10", "ing-3", "ing-17", "ing-4", "ing-11"], "Pinni"),
];

export const MOCK_PRODUCT_INGREDIENTS: { product_id: string; ingredient_id: string }[] =
  RAW_PRODUCTS.flatMap((p) =>
    p.ingredientIds.map((iid) => ({ product_id: p.product.id, ingredient_id: iid }))
  );

export const MOCK_PRODUCTS_RAW: Tables<"products">[] = RAW_PRODUCTS.map((p) => p.product);
export const MOCK_VARIANTS: Tables<"product_variants">[] = RAW_PRODUCTS.flatMap((p) => p.variants);

export const MOCK_PRODUCTS: Product[] = RAW_PRODUCTS.map((p) => ({
  ...p.product,
  category: MOCK_CATEGORIES.find((c) => c.id === p.product.category_id),
  variants: p.variants,
  ingredients: p.ingredientIds
    .map((iid) => MOCK_INGREDIENTS.find((ing) => ing.id === iid)!)
    .filter(Boolean),
}));

export const MOCK_CATERING_EVENTS: Tables<"catering_events">[] = [
  { id: "ev-1", title: "Grand Wedding Reception", description: "Full-service wedding catering for 500+ guests with live counters, dessert stations, and a royal dining experience.", image_url: "https://placehold.co/600x400/FEF3C7/78350F?text=Wedding", event_type: "wedding", created_at: new Date().toISOString() },
  { id: "ev-2", title: "Corporate Annual Gala", description: "Elegant multi-course dining for corporate events with curated menus and professional service staff.", image_url: "https://placehold.co/600x400/FDE68A/78350F?text=Corporate", event_type: "corporate", created_at: new Date().toISOString() },
  { id: "ev-3", title: "Birthday Celebrations", description: "Customized menus and themed setups for milestone celebrations, from intimate gatherings to grand parties.", image_url: "https://placehold.co/600x400/FCD34D/78350F?text=Birthday", event_type: "birthday", created_at: new Date().toISOString() },
  { id: "ev-4", title: "Festival & Puja Catering", description: "Traditional sweets and savory spreads for Diwali, Navratri, Ganesh Chaturthi, and other festive occasions.", image_url: "https://placehold.co/600x400/FBBF24/78350F?text=Festival", event_type: "festival", created_at: new Date().toISOString() },
  { id: "ev-5", title: "Engagement & Sangeet Night", description: "Vibrant menus with chaat counters, live stations, and curated pairings for pre-wedding events.", image_url: "https://placehold.co/600x400/F59E0B/78350F?text=Engagement", event_type: "wedding", created_at: new Date().toISOString() },
];

export const MOCK_CATERING_MENU_ITEMS: Tables<"catering_menu_items">[] = [
  // ── BREAKFAST ──
  { id: "m-1", name: "Tea, Coffee & Green Tea", category: "Beverages", service_time: "breakfast", price_per_person: 25, description: "Chai, coffee, green tea, lemon tea with warm milk", is_available: true, created_at: new Date().toISOString() },
  { id: "m-2", name: "Fresh Juice Station", category: "Beverages", service_time: "breakfast", price_per_person: 35, description: "Seasonal fruit juices — orange, watermelon, pineapple", is_available: true, created_at: new Date().toISOString() },
  { id: "m-3", name: "Bread Butter Jam", category: "Light Bites", service_time: "breakfast", price_per_person: 20, description: "White and brown bread with butter, jam, and honey", is_available: true, created_at: new Date().toISOString() },
  { id: "m-4", name: "Cornflakes & Chocos", category: "Light Bites", service_time: "breakfast", price_per_person: 25, description: "Cereal station with warm and cold milk", is_available: true, created_at: new Date().toISOString() },
  { id: "m-5", name: "Badami Mistri", category: "Sweets", service_time: "breakfast", price_per_person: 30, description: "Traditional almond-flavoured sweet preparation", is_available: true, created_at: new Date().toISOString() },
  { id: "m-6", name: "Murabba (Amla & Apple)", category: "Accompaniments", service_time: "breakfast", price_per_person: 15, description: "Sweet preserved amla and apple murabba", is_available: true, created_at: new Date().toISOString() },
  { id: "m-7", name: "Paratha Station", category: "North Indian", service_time: "breakfast", price_per_person: 55, description: "Sada, aloo, masala parathas with dahi and pickle", is_available: true, created_at: new Date().toISOString() },
  { id: "m-8", name: "Poha", category: "Light Bites", service_time: "breakfast", price_per_person: 35, description: "Fresh poha with sev, lemon, and coriander", is_available: true, created_at: new Date().toISOString() },
  { id: "m-9", name: "Upma", category: "South Indian", service_time: "breakfast", price_per_person: 35, description: "Rava upma tempered with mustard and curry leaves", is_available: true, created_at: new Date().toISOString() },
  { id: "m-10", name: "Idli & Sambar", category: "South Indian", service_time: "breakfast", price_per_person: 45, description: "Steamed idlis with sambar and coconut chutney", is_available: true, created_at: new Date().toISOString() },
  { id: "m-11", name: "Medu Vada", category: "South Indian", service_time: "breakfast", price_per_person: 40, description: "Crispy urad dal vadas with sambar and chutney", is_available: true, created_at: new Date().toISOString() },
  { id: "m-12", name: "Masala Dosa", category: "South Indian", service_time: "breakfast", price_per_person: 50, description: "Crispy dosa with potato filling, sambar, and chutneys", is_available: true, created_at: new Date().toISOString() },
  { id: "m-13", name: "Chhola Bhatura", category: "North Indian", service_time: "breakfast", price_per_person: 60, description: "Spiced chickpea curry with fluffy fried bhatura", is_available: true, created_at: new Date().toISOString() },
  { id: "m-14", name: "Khaman Dhokla", category: "Gujarati", service_time: "breakfast", price_per_person: 40, description: "Steamed gram flour dhokla with tadka", is_available: true, created_at: new Date().toISOString() },
  { id: "m-15", name: "Chuntiya Roti & Ker Sangri", category: "Rajasthani", service_time: "breakfast", price_per_person: 35, description: "Traditional thin roti with ker sangri pickle", is_available: true, created_at: new Date().toISOString() },
  { id: "m-16", name: "Bajri Daliya", category: "Rajasthani", service_time: "breakfast", price_per_person: 30, description: "Millet porridge — a traditional Rajasthani breakfast", is_available: true, created_at: new Date().toISOString() },
  { id: "m-17", name: "Gujarati Khakhra", category: "Gujarati", service_time: "breakfast", price_per_person: 20, description: "Crispy thin rotis, assorted flavours", is_available: true, created_at: new Date().toISOString() },
  { id: "m-18", name: "Fresh Fruit Platter", category: "Fruits", service_time: "breakfast", price_per_person: 40, description: "Watermelon, papaya, grapes, apple, seasonal fruits", is_available: true, created_at: new Date().toISOString() },
  { id: "m-19", name: "Green Sandwich", category: "Light Bites", service_time: "breakfast", price_per_person: 30, description: "Grilled vegetable sandwiches with mint chutney", is_available: true, created_at: new Date().toISOString() },
  { id: "m-20", name: "Bedmi Puri & Aloo Sabji", category: "North Indian", service_time: "breakfast", price_per_person: 55, description: "Spiced dal-stuffed puris with rich aloo sabji", is_available: true, created_at: new Date().toISOString() },
  { id: "m-21", name: "Bread Pakoda", category: "Snacks", service_time: "breakfast", price_per_person: 30, description: "Bread slices stuffed with potato, batter-fried", is_available: true, created_at: new Date().toISOString() },
  { id: "m-22", name: "Gond Pak", category: "Sweets", service_time: "breakfast", price_per_person: 45, description: "Traditional gum-based Rajasthani sweet", is_available: true, created_at: new Date().toISOString() },
  { id: "m-23", name: "Rasgulla", category: "Sweets", service_time: "breakfast", price_per_person: 25, description: "Soft chenna balls in light sugar syrup", is_available: true, created_at: new Date().toISOString() },

  // ── LUNCH ──
  { id: "m-24", name: "Motipak", category: "Sweets", service_time: "lunch", price_per_person: 35, description: "Traditional boondi ladoo-style sweet", is_available: true, created_at: new Date().toISOString() },
  { id: "m-25", name: "Gulab Jamun", category: "Sweets", service_time: "lunch", price_per_person: 25, description: "Soft milk dumplings in rose-scented syrup", is_available: true, created_at: new Date().toISOString() },
  { id: "m-26", name: "Rajbhog", category: "Sweets", service_time: "lunch", price_per_person: 35, description: "Saffron-flavoured rasgulla with dry fruit filling", is_available: true, created_at: new Date().toISOString() },
  { id: "m-27", name: "Shrikhand", category: "Sweets", service_time: "lunch", price_per_person: 30, description: "Creamy hung-curd dessert flavoured with saffron and cardamom", is_available: true, created_at: new Date().toISOString() },
  { id: "m-28", name: "Kesar Kaju Kasata", category: "Sweets", service_time: "lunch", price_per_person: 45, description: "Rich saffron and cashew sweet roll", is_available: true, created_at: new Date().toISOString() },
  { id: "m-29", name: "Paneer Lababdar", category: "Main Course", service_time: "lunch", price_per_person: 55, description: "Paneer in rich tomato-cashew gravy", is_available: true, created_at: new Date().toISOString() },
  { id: "m-30", name: "Gobi Matar", category: "Main Course", service_time: "lunch", price_per_person: 40, description: "Cauliflower and peas in spiced gravy", is_available: true, created_at: new Date().toISOString() },
  { id: "m-31", name: "Aloo Dum", category: "Main Course", service_time: "lunch", price_per_person: 35, description: "Baby potatoes in rich spiced gravy", is_available: true, created_at: new Date().toISOString() },
  { id: "m-32", name: "Paneer Kofta", category: "Main Course", service_time: "lunch", price_per_person: 55, description: "Stuffed paneer dumplings in creamy gravy", is_available: true, created_at: new Date().toISOString() },
  { id: "m-33", name: "Kadhi Pakodi", category: "Main Course", service_time: "lunch", price_per_person: 35, description: "Yogurt-based curry with gram flour pakodis", is_available: true, created_at: new Date().toISOString() },
  { id: "m-34", name: "Gatta Sabji", category: "Rajasthani", service_time: "lunch", price_per_person: 40, description: "Besan gattas in spiced yogurt gravy", is_available: true, created_at: new Date().toISOString() },
  { id: "m-35", name: "Ker Sangri Sabji", category: "Rajasthani", service_time: "lunch", price_per_person: 35, description: "Desert beans and berries — classic Rajasthani dish", is_available: true, created_at: new Date().toISOString() },
  { id: "m-36", name: "Dal Bati Churma", category: "Rajasthani", service_time: "lunch", price_per_person: 75, description: "Traditional baked bati with panchmel dal, churma, and ghee", is_available: true, created_at: new Date().toISOString() },
  { id: "m-37", name: "Masala Bati & Mawa Bati", category: "Rajasthani", service_time: "lunch", price_per_person: 60, description: "Spiced and mawa-stuffed batis with dal", is_available: true, created_at: new Date().toISOString() },
  { id: "m-38", name: "Bhunjwa Lapsi", category: "Rajasthani", service_time: "lunch", price_per_person: 30, description: "Sweet broken wheat dessert with ghee", is_available: true, created_at: new Date().toISOString() },
  { id: "m-39", name: "Doha Rabdi", category: "Rajasthani", service_time: "lunch", price_per_person: 35, description: "Traditional Rajasthani curd-based dessert", is_available: true, created_at: new Date().toISOString() },
  { id: "m-40", name: "Dahi Bada", category: "Chaat", service_time: "lunch", price_per_person: 30, description: "Soft urad dal vadas in sweet yogurt with chutneys", is_available: true, created_at: new Date().toISOString() },
  { id: "m-41", name: "Shahi Samosa", category: "Starters", service_time: "lunch", price_per_person: 35, description: "Rich samosa with dry fruit and mawa filling", is_available: true, created_at: new Date().toISOString() },
  { id: "m-42", name: "Onion Patti", category: "Side", service_time: "lunch", price_per_person: 25, description: "Crispy onion-stuffed pastry strips", is_available: true, created_at: new Date().toISOString() },
  { id: "m-43", name: "Bundi Rayta", category: "Accompaniments", service_time: "lunch", price_per_person: 15, description: "Curd with seasoned boondi", is_available: true, created_at: new Date().toISOString() },
  { id: "m-44", name: "Falka & Missi Roti", category: "Breads", service_time: "lunch", price_per_person: 20, description: "Thin wheat roti and besan missi roti", is_available: true, created_at: new Date().toISOString() },
  { id: "m-45", name: "Bajri & Chana Roti", category: "Breads", service_time: "lunch", price_per_person: 20, description: "Traditional millet and chana flour rotis", is_available: true, created_at: new Date().toISOString() },
  { id: "m-46", name: "Dal Chawal", category: "Rice", service_time: "lunch", price_per_person: 25, description: "Panchmel dal with steamed basmati rice", is_available: true, created_at: new Date().toISOString() },
  { id: "m-47", name: "Jeera Rice", category: "Rice", service_time: "lunch", price_per_person: 25, description: "Basmati rice tempered with cumin seeds", is_available: true, created_at: new Date().toISOString() },
  { id: "m-48", name: "Gatta Pulav", category: "Rice", service_time: "lunch", price_per_person: 45, description: "Rajasthani rice pilaf with besan gattas", is_available: true, created_at: new Date().toISOString() },
  { id: "m-49", name: "Green Salad & Papad", category: "Accompaniments", service_time: "lunch", price_per_person: 15, description: "Fresh greens, onion, papad, and disco papad", is_available: true, created_at: new Date().toISOString() },
  { id: "m-50", name: "Pickle & Chutney Platter", category: "Accompaniments", service_time: "lunch", price_per_person: 10, description: "Onion pickle, garlic chutney, green chilli, mix achar", is_available: true, created_at: new Date().toISOString() },
  { id: "m-51", name: "Ghee, Gud & Shakkar", category: "Accompaniments", service_time: "lunch", price_per_person: 10, description: "Pure ghee, jaggery, and sugar", is_available: true, created_at: new Date().toISOString() },
  { id: "m-52", name: "Kesariya Ice Cream", category: "Dessert", service_time: "lunch", price_per_person: 40, description: "Traditional saffron kesar ice cream (Sardarshahar style)", is_available: true, created_at: new Date().toISOString() },
  { id: "m-53", name: "Meva Khichdi", category: "Rajasthani", service_time: "lunch", price_per_person: 50, description: "Rich khichdi with dry fruits, ghee, and spices", is_available: true, created_at: new Date().toISOString() },

  // ── SNACKS / HI TEA ──
  { id: "m-54", name: "Gol Gappa Counter", category: "Chaat", service_time: "snacks", price_per_person: 35, description: "Live pani puri station with flavoured waters", is_available: true, created_at: new Date().toISOString() },
  { id: "m-55", name: "Raj Kachori", category: "Chaat", service_time: "snacks", price_per_person: 40, description: "Large crispy kachori filled with curd and chutneys", is_available: true, created_at: new Date().toISOString() },
  { id: "m-56", name: "Bhelpuri & Jhalmuri", category: "Chaat", service_time: "snacks", price_per_person: 30, description: "Puffed rice chaat — Mumbai and Bengali style", is_available: true, created_at: new Date().toISOString() },
  { id: "m-57", name: "Dahi Bhalla Chaat", category: "Chaat", service_time: "snacks", price_per_person: 35, description: "Soft vadas in curd with tamarind and mint chutney", is_available: true, created_at: new Date().toISOString() },
  { id: "m-58", name: "Sweet Corn Chaat", category: "Chaat", service_time: "snacks", price_per_person: 30, description: "Butter-tossed sweet corn with masala", is_available: true, created_at: new Date().toISOString() },
  { id: "m-59", name: "Aloo Tikki", category: "Chaat", service_time: "snacks", price_per_person: 30, description: "Crispy potato patties with chutneys and curd", is_available: true, created_at: new Date().toISOString() },
  { id: "m-60", name: "Pan Patta Chaat", category: "Chaat", service_time: "snacks", price_per_person: 35, description: "Betel leaf chaat with sweet and tangy filling", is_available: true, created_at: new Date().toISOString() },
  { id: "m-61", name: "Onion Kachori", category: "Snacks", service_time: "snacks", price_per_person: 30, description: "Crispy onion-stuffed kachori with green chutney", is_available: true, created_at: new Date().toISOString() },
  { id: "m-62", name: "Matar Kachori & Pestry", category: "Snacks", service_time: "snacks", price_per_person: 35, description: "Green peas kachori with bakery pastries", is_available: true, created_at: new Date().toISOString() },
  { id: "m-63", name: "Samosa Counter", category: "Snacks", service_time: "snacks", price_per_person: 30, description: "Crispy samosas with sweet and green chutney", is_available: true, created_at: new Date().toISOString() },
  { id: "m-64", name: "Paneer Pakoda & Mix Pakoda", category: "Snacks", service_time: "snacks", price_per_person: 40, description: "Assorted pakodas — paneer, onion, and mixed vegetable", is_available: true, created_at: new Date().toISOString() },
  { id: "m-65", name: "Club Kachori", category: "Snacks", service_time: "snacks", price_per_person: 45, description: "Layered kachori with aloo sabji — street food style", is_available: true, created_at: new Date().toISOString() },
  { id: "m-66", name: "Masala Chai & Cold Drinks", category: "Beverages", service_time: "snacks", price_per_person: 20, description: "Hot masala chai, juices, and cold beverages", is_available: true, created_at: new Date().toISOString() },
  { id: "m-67", name: "Maggi Station", category: "Live Counter", service_time: "snacks", price_per_person: 30, description: "Live maggi counter with assorted toppings", is_available: true, created_at: new Date().toISOString() },
  { id: "m-68", name: "Variety Dosa Counter", category: "Live Counter", service_time: "snacks", price_per_person: 50, description: "Rava dosa, masala dosa, and cheese dosa — live", is_available: true, created_at: new Date().toISOString() },
  { id: "m-69", name: "French Fries & Chaat Papdi", category: "Snacks", service_time: "snacks", price_per_person: 30, description: "French fries and papdi chaat combo", is_available: true, created_at: new Date().toISOString() },
  { id: "m-70", name: "Fruit Counter (2 varieties)", category: "Fruits", service_time: "snacks", price_per_person: 25, description: "Seasonal sliced fruits", is_available: true, created_at: new Date().toISOString() },
  { id: "m-71", name: "Mithai (1 variety)", category: "Sweets", service_time: "snacks", price_per_person: 25, description: "One variety of fresh Indian sweet", is_available: true, created_at: new Date().toISOString() },

  // ── DINNER ──
  { id: "m-72", name: "Badam Katli", category: "Sweets", service_time: "dinner", price_per_person: 40, description: "Thin almond fudge slices with pista topping", is_available: true, created_at: new Date().toISOString() },
  { id: "m-73", name: "Rasmalai", category: "Sweets", service_time: "dinner", price_per_person: 35, description: "Soft chenna discs in saffron-cardamom milk", is_available: true, created_at: new Date().toISOString() },
  { id: "m-74", name: "Pineapple Halwa", category: "Sweets", service_time: "dinner", price_per_person: 30, description: "Warm pineapple halwa garnished with dry fruits", is_available: true, created_at: new Date().toISOString() },
  { id: "m-75", name: "Malai Paan", category: "Sweets", service_time: "dinner", price_per_person: 30, description: "Betel leaf shaped sweet with cream and gulkand filling", is_available: true, created_at: new Date().toISOString() },
  { id: "m-76", name: "Malai Roll", category: "Sweets", service_time: "dinner", price_per_person: 30, description: "Rolled cream sweet with pistachio garnish", is_available: true, created_at: new Date().toISOString() },
  { id: "m-77", name: "Jalebi with Rabri", category: "Sweets", service_time: "dinner", price_per_person: 35, description: "Hot crispy jalebis with thick rabri", is_available: true, created_at: new Date().toISOString() },
  { id: "m-78", name: "Malai Ghevar", category: "Sweets", service_time: "dinner", price_per_person: 40, description: "Rajasthani disc-shaped sweet soaked in syrup, topped with cream", is_available: true, created_at: new Date().toISOString() },
  { id: "m-79", name: "Shahi Paneer", category: "Main Course", service_time: "dinner", price_per_person: 60, description: "Royal paneer in rich cream and cashew gravy", is_available: true, created_at: new Date().toISOString() },
  { id: "m-80", name: "Paneer Butter Masala", category: "Main Course", service_time: "dinner", price_per_person: 55, description: "Creamy paneer in tomato-butter gravy", is_available: true, created_at: new Date().toISOString() },
  { id: "m-81", name: "Palak Paneer", category: "Main Course", service_time: "dinner", price_per_person: 50, description: "Paneer cubes in smooth spinach gravy", is_available: true, created_at: new Date().toISOString() },
  { id: "m-82", name: "Malai Kofta", category: "Main Course", service_time: "dinner", price_per_person: 55, description: "Cottage cheese dumplings in creamy cashew gravy", is_available: true, created_at: new Date().toISOString() },
  { id: "m-83", name: "Malai Matar", category: "Main Course", service_time: "dinner", price_per_person: 45, description: "Green peas in rich cream and cashew sauce", is_available: true, created_at: new Date().toISOString() },
  { id: "m-84", name: "Achari Aloo", category: "Main Course", service_time: "dinner", price_per_person: 35, description: "Potatoes in pickle-spiced tangy gravy", is_available: true, created_at: new Date().toISOString() },
  { id: "m-85", name: "Govind Gatta", category: "Rajasthani", service_time: "dinner", price_per_person: 45, description: "Stuffed besan gattas in rich gravy", is_available: true, created_at: new Date().toISOString() },
  { id: "m-86", name: "Kaju Keri Sabji", category: "Rajasthani", service_time: "dinner", price_per_person: 50, description: "Cashew and raw mango in a sweet-spicy curry", is_available: true, created_at: new Date().toISOString() },
  { id: "m-87", name: "Stuffed Bhindi", category: "Main Course", service_time: "dinner", price_per_person: 40, description: "Okra stuffed with spiced masala, pan-roasted", is_available: true, created_at: new Date().toISOString() },
  { id: "m-88", name: "Dal Makhani", category: "Main Course", service_time: "dinner", price_per_person: 45, description: "Slow-cooked black dal with butter and cream", is_available: true, created_at: new Date().toISOString() },
  { id: "m-89", name: "Dal Fry / Dal Tadka", category: "Main Course", service_time: "dinner", price_per_person: 30, description: "Tempered yellow dal with ghee and cumin", is_available: true, created_at: new Date().toISOString() },
  { id: "m-90", name: "Tawa Sabji (Live)", category: "Live Counter", service_time: "dinner", price_per_person: 45, description: "Live tawa with assorted vegetable stir-fry", is_available: true, created_at: new Date().toISOString() },
  { id: "m-91", name: "Tandoori Roti & Baby Naan", category: "Breads", service_time: "dinner", price_per_person: 25, description: "Assorted tandoor breads — plain naan, garlic naan, roti", is_available: true, created_at: new Date().toISOString() },
  { id: "m-92", name: "Rumali Roti", category: "Breads", service_time: "dinner", price_per_person: 20, description: "Paper-thin handkerchief bread", is_available: true, created_at: new Date().toISOString() },
  { id: "m-93", name: "Lachha Parantha", category: "Breads", service_time: "dinner", price_per_person: 25, description: "Flaky layered parantha from tandoor", is_available: true, created_at: new Date().toISOString() },
  { id: "m-94", name: "Falka & Missi Roti", category: "Breads", service_time: "dinner", price_per_person: 20, description: "Thin wheat roti and besan missi roti", is_available: true, created_at: new Date().toISOString() },
  { id: "m-95", name: "Makki Roti & Sarson Saag", category: "Punjabi", service_time: "dinner", price_per_person: 50, description: "Corn flour roti with mustard greens — Punjabi classic", is_available: true, created_at: new Date().toISOString() },
  { id: "m-96", name: "Dal Chawal", category: "Rice", service_time: "dinner", price_per_person: 25, description: "Panchmel dal with steamed basmati rice", is_available: true, created_at: new Date().toISOString() },
  { id: "m-97", name: "Hyderabadi Biryani", category: "Rice", service_time: "dinner", price_per_person: 70, description: "Fragrant dum biryani with raita", is_available: true, created_at: new Date().toISOString() },
  { id: "m-98", name: "Jeera Rice", category: "Rice", service_time: "dinner", price_per_person: 25, description: "Basmati rice tempered with cumin seeds", is_available: true, created_at: new Date().toISOString() },
  { id: "m-99", name: "Jodhpuri Kabuli", category: "Rice", service_time: "dinner", price_per_person: 50, description: "Rich Rajasthani chickpea-sweet rice pulav", is_available: true, created_at: new Date().toISOString() },
  { id: "m-100", name: "Mix Raita", category: "Accompaniments", service_time: "dinner", price_per_person: 15, description: "Seasoned yogurt with mixed vegetables", is_available: true, created_at: new Date().toISOString() },
  { id: "m-101", name: "Green Salad & Sprouts", category: "Accompaniments", service_time: "dinner", price_per_person: 15, description: "Fresh greens, sprouts — moong, moth, chana", is_available: true, created_at: new Date().toISOString() },
  { id: "m-102", name: "Papad & Disco Papad", category: "Accompaniments", service_time: "dinner", price_per_person: 10, description: "Roasted and masala-topped papads", is_available: true, created_at: new Date().toISOString() },
  { id: "m-103", name: "Pickle & Chutney Platter", category: "Accompaniments", service_time: "dinner", price_per_person: 10, description: "Onion pickle, garlic chutney, green chilli, mix achar", is_available: true, created_at: new Date().toISOString() },
  { id: "m-104", name: "Live Ice Cream (2-3 flavours)", category: "Dessert", service_time: "dinner", price_per_person: 50, description: "Live ice cream counter — kesar gulfi, rajbhog, American nuts", is_available: true, created_at: new Date().toISOString() },
  { id: "m-105", name: "Fruit Counter (Indian + Imported)", category: "Fruits", service_time: "dinner", price_per_person: 60, description: "4 Indian + 6 imported seasonal fruits", is_available: true, created_at: new Date().toISOString() },
  { id: "m-106", name: "Paan Counter", category: "Live Counter", service_time: "dinner", price_per_person: 20, description: "Assorted meetha paan — gulkand, chocolate, fire paan", is_available: true, created_at: new Date().toISOString() },
  { id: "m-107", name: "Fancy Salad Counter (4 types)", category: "Salad", service_time: "dinner", price_per_person: 30, description: "Russian, pasta, coleslaw, and sprout salads", is_available: true, created_at: new Date().toISOString() },
  { id: "m-108", name: "Namkeen & Mixture (4 types)", category: "Namkeen", service_time: "dinner", price_per_person: 20, description: "Assorted namkeens — bhujia, mixture, sev, shakarpara", is_available: true, created_at: new Date().toISOString() },
  { id: "m-109", name: "Soup Station", category: "Starters", service_time: "dinner", price_per_person: 30, description: "Tomato, sweet corn, and hot & sour soups", is_available: true, created_at: new Date().toISOString() },
  { id: "m-110", name: "Kadai Paneer", category: "Main Course", service_time: "dinner", price_per_person: 55, description: "Paneer and peppers in aromatic kadai masala", is_available: true, created_at: new Date().toISOString() },

  // ── LATE NIGHT ──
  { id: "m-111", name: "Welcome Drinks & Mocktails (5 types)", category: "Beverages", service_time: "late_night", price_per_person: 45, description: "Paan gulkand shake, oreo shake, mix juices, and assorted mocktails", is_available: true, created_at: new Date().toISOString() },
  { id: "m-112", name: "Honey Chilli Paneer", category: "Starters", service_time: "late_night", price_per_person: 50, description: "Indo-Chinese crispy paneer tossed in honey chilli sauce", is_available: true, created_at: new Date().toISOString() },
  { id: "m-113", name: "Paneer Tikka", category: "Starters", service_time: "late_night", price_per_person: 55, description: "Marinated paneer grilled in tandoor", is_available: true, created_at: new Date().toISOString() },
  { id: "m-114", name: "Hara Bhara Kabab", category: "Starters", service_time: "late_night", price_per_person: 40, description: "Spinach and green peas patties, shallow-fried", is_available: true, created_at: new Date().toISOString() },
  { id: "m-115", name: "Soya Stick Chop", category: "Starters", service_time: "late_night", price_per_person: 40, description: "Crispy soya chaap sticks with dipping sauce", is_available: true, created_at: new Date().toISOString() },
  { id: "m-116", name: "Cheese Balls", category: "Starters", service_time: "late_night", price_per_person: 45, description: "Golden fried cheese balls with marinara dip", is_available: true, created_at: new Date().toISOString() },
  { id: "m-117", name: "Paneer 65", category: "Starters", service_time: "late_night", price_per_person: 50, description: "South Indian-style spicy fried paneer bites", is_available: true, created_at: new Date().toISOString() },
  { id: "m-118", name: "Spring Roll", category: "Starters", service_time: "late_night", price_per_person: 40, description: "Crispy rolls stuffed with vegetables", is_available: true, created_at: new Date().toISOString() },
  { id: "m-119", name: "French Fries & Potato Bites", category: "Starters", service_time: "late_night", price_per_person: 35, description: "Crispy fries and herbed potato bites", is_available: true, created_at: new Date().toISOString() },
  { id: "m-120", name: "Pasta Station (Red & White)", category: "Live Counter", service_time: "late_night", price_per_person: 45, description: "Live pasta counter with arabiata and alfredo sauces", is_available: true, created_at: new Date().toISOString() },
  { id: "m-121", name: "Mini Pizza Counter", category: "Live Counter", service_time: "late_night", price_per_person: 45, description: "Assorted mini pizzas — margherita, corn, paneer", is_available: true, created_at: new Date().toISOString() },
  { id: "m-122", name: "Momos Station", category: "Live Counter", service_time: "late_night", price_per_person: 40, description: "Steamed and fried momos with schezwan chutney", is_available: true, created_at: new Date().toISOString() },
  { id: "m-123", name: "Manchurian & Noodles", category: "Live Counter", service_time: "late_night", price_per_person: 45, description: "Veg manchurian with hakka noodles — live counter", is_available: true, created_at: new Date().toISOString() },
  { id: "m-124", name: "Pav Bhaji Counter", category: "Live Counter", service_time: "late_night", price_per_person: 40, description: "Mumbai-style pav bhaji with butter and lemon", is_available: true, created_at: new Date().toISOString() },
  { id: "m-125", name: "Chuski Counter", category: "Live Counter", service_time: "late_night", price_per_person: 20, description: "Flavoured ice gola — kala khatta, orange, mango", is_available: true, created_at: new Date().toISOString() },
  { id: "m-126", name: "Mangoliya Counter", category: "Live Counter", service_time: "late_night", price_per_person: 30, description: "Traditional Rajasthani mangoliya preparation", is_available: true, created_at: new Date().toISOString() },
  { id: "m-127", name: "Chaumin & Soup Counter", category: "Live Counter", service_time: "late_night", price_per_person: 35, description: "Hot chowmein noodles and assorted soups", is_available: true, created_at: new Date().toISOString() },
  { id: "m-128", name: "Mini Sweets (2 types)", category: "Sweets", service_time: "late_night", price_per_person: 25, description: "Bite-sized assorted Indian sweets", is_available: true, created_at: new Date().toISOString() },
];

export const MOCK_CATERING_ADDONS: Tables<"catering_addons">[] = [
  { id: "a-1", name: "Basic Counter Setup", addon_type: "counter", price: 5000, description: "Standard serving counters with clean linen", created_at: new Date().toISOString() },
  { id: "a-2", name: "Premium Counter Setup", addon_type: "counter", price: 12000, description: "Elegant counters with flowers and chafing dishes", created_at: new Date().toISOString() },
  { id: "a-3", name: "Royal Counter Setup", addon_type: "counter", price: 25000, description: "Luxury designer counters with floral arrangements", created_at: new Date().toISOString() },
  { id: "a-4", name: "Service Waiter", addon_type: "service_staff", price: 1500, description: "Professional waiter per day", created_at: new Date().toISOString() },
  { id: "a-5", name: "Head Chef On-site", addon_type: "service_staff", price: 5000, description: "Experienced head chef on location", created_at: new Date().toISOString() },
  { id: "a-6", name: "Floral Centerpieces", addon_type: "decoration", price: 500, description: "Fresh flowers for each table", created_at: new Date().toISOString() },
  { id: "a-7", name: "LED Lighting", addon_type: "decoration", price: 8000, description: "Ambient LED lighting for dining area", created_at: new Date().toISOString() },
  { id: "a-8", name: "Steel Crockery", addon_type: "crockery", price: 30, description: "Stainless steel plates and cutlery per person", created_at: new Date().toISOString() },
];
